#!/bin/sh
#
# Executes an MPI executable image using the logical cores reported by the _NPROCESSORS_ONLN environment variable
#
clear
if [ $# -eq 1 ]
  then
    echo -e "Will run $1 using `getconf _NPROCESSORS_ONLN` CPUs (logical cores) on host `hostname`:\n`lscpu | egrep 'Model name|Socket|Thread|NUMA|cache'` \n"
    echo -e "$1 output:\n"
    mpiexec -n `getconf _NPROCESSORS_ONLN` $1
    echo -e ""
  else
    echo "Syntax: $0 requires one argument (the name of an MPI executable image)"
fi
